import { supabase } from './supabase'

const SCAN_BUCKET = 'form-scans'

const DISCLAIMER_TEXT =
  'I hereby acknowledge that SASEC Engineering PVT. LTD. holds no responsibility for ' +
  'any accidents, injuries, or incidents that occur outside the work premises during the ' +
  'leave period. The employee takes full personal responsibility for their safety during leave.'

// ── Base print styles used by both forms ─────────────────────

const PRINT_BASE_CSS = `
  *, *::before, *::after { box-sizing: border-box; margin: 0; padding: 0; }
  body {
    font-family: 'Arial', sans-serif;
    font-size: 13px;
    color: #111;
    padding: 40px 50px;
    max-width: 800px;
    margin: 0 auto;
    line-height: 1.6;
  }
  .header {
    display: flex;
    align-items: center;
    gap: 18px;
    border-bottom: 2px solid #C0272D;
    padding-bottom: 16px;
    margin-bottom: 24px;
  }
  .logo { width: 60px; height: 60px; object-fit: contain; }
  .company-name { font-size: 16px; font-weight: 700; color: #0E1733; line-height: 1.3; }
  .company-sub  { font-size: 11px; color: #666; }
  .form-title {
    font-size: 15px; font-weight: 700; color: #C0272D;
    text-transform: uppercase; letter-spacing: 0.5px;
    margin-bottom: 20px;
  }
  .field-grid { display: grid; grid-template-columns: 1fr 1fr; gap: 14px 28px; margin-bottom: 24px; }
  .field { border-bottom: 1px solid #ccc; padding-bottom: 4px; }
  .field-label { font-size: 10px; color: #666; text-transform: uppercase; letter-spacing: 0.4px; }
  .field-value { font-size: 13px; font-weight: 600; color: #111; min-height: 20px; }
  .field-full   { grid-column: 1 / -1; }
  .disclaimer-box {
    background: #f9f9f9;
    border: 1px solid #ddd;
    border-left: 4px solid #C0272D;
    padding: 14px 16px;
    margin-bottom: 32px;
    font-size: 12px;
    line-height: 1.7;
    font-style: italic;
  }
  .disclaimer-title { font-weight: 700; font-style: normal; margin-bottom: 6px; color: #C0272D; }
  .sig-row {
    display: grid;
    grid-template-columns: 1fr 1fr;
    gap: 40px;
    margin-top: 40px;
  }
  .sig-box .line { border-bottom: 1px solid #333; height: 40px; margin-bottom: 4px; }
  .sig-box .label { font-size: 10px; color: #666; text-transform: uppercase; }
  .footer {
    margin-top: 40px;
    border-top: 1px solid #ddd;
    padding-top: 10px;
    font-size: 10px;
    color: #999;
    text-align: center;
  }
  @media print {
    @page { size: A4; margin: 20mm 25mm; }
    body { padding: 0; }
  }
`

function logoUrl() {
  return window.location.origin + '/logo.png'
}

// ── Print: Leave Disclaimer ───────────────────────────────────

export function printLeaveDisclaimer(data) {
  const win = window.open('', '_blank', 'width=820,height=1100')
  if (!win) { alert('Please allow pop-ups to print.'); return }

  win.document.write(`<!DOCTYPE html><html lang="en"><head>
  <meta charset="UTF-8">
  <title>Leave Disclaimer — SASEC Engineering</title>
  <style>${PRINT_BASE_CSS}</style>
</head><body>
  <div class="header">
    <img class="logo" src="${logoUrl()}" alt="SASEC">
    <div>
      <div class="company-name">SASEC Engineering PVT. LTD.</div>
      <div class="company-sub">Swamy &amp; Sons &middot; Engineers | Contractors</div>
    </div>
  </div>

  <div class="form-title">Leave Disclaimer Form</div>

  <div class="field-grid">
    <div class="field">
      <div class="field-label">Worker Name</div>
      <div class="field-value">${esc(data.workerName)}</div>
    </div>
    <div class="field">
      <div class="field-label">Worker Phone</div>
      <div class="field-value">${esc(data.workerPhone) || '—'}</div>
    </div>
    <div class="field">
      <div class="field-label">Leave Start Date</div>
      <div class="field-value">${esc(data.leaveStart)}</div>
    </div>
    <div class="field">
      <div class="field-label">Leave End Date</div>
      <div class="field-value">${esc(data.leaveEnd)}</div>
    </div>
    <div class="field">
      <div class="field-label">Supervisor Name</div>
      <div class="field-value">${esc(data.supervisorName)}</div>
    </div>
    <div class="field">
      <div class="field-label">Date of Declaration</div>
      <div class="field-value">${new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'long', year:'numeric' })}</div>
    </div>
  </div>

  <div class="disclaimer-box">
    <div class="disclaimer-title">Disclaimer</div>
    ${esc(DISCLAIMER_TEXT)}
  </div>

  <div class="sig-row">
    <div class="sig-box">
      <div class="line"></div>
      <div class="label">Worker Signature</div>
    </div>
    <div class="sig-box">
      <div class="line"></div>
      <div class="label">Supervisor Signature &amp; Stamp</div>
    </div>
  </div>

  <div class="footer">
    Generated by SASEC Engineering Internal Portal &mdash; ${new Date().toLocaleString('en-IN')}
  </div>

  <script>
    window.addEventListener('load', function() {
      window.print();
      window.addEventListener('afterprint', function() { window.close(); });
    });
  </script>
</body></html>`)
  win.document.close()
}

// ── Print: Onboarding Form ────────────────────────────────────

export function printOnboardingForm(data) {
  const win = window.open('', '_blank', 'width=820,height=1200')
  if (!win) { alert('Please allow pop-ups to print.'); return }

  win.document.write(`<!DOCTYPE html><html lang="en"><head>
  <meta charset="UTF-8">
  <title>Worker Onboarding — SASEC Engineering</title>
  <style>${PRINT_BASE_CSS}</style>
</head><body>
  <div class="header">
    <img class="logo" src="${logoUrl()}" alt="SASEC">
    <div>
      <div class="company-name">SASEC Engineering PVT. LTD.</div>
      <div class="company-sub">Swamy &amp; Sons &middot; Engineers | Contractors</div>
    </div>
  </div>

  <div class="form-title">Worker Onboarding Form</div>

  <div class="field-grid">
    <div class="field">
      <div class="field-label">Full Name</div>
      <div class="field-value">${esc(data.fullName)}</div>
    </div>
    <div class="field">
      <div class="field-label">Phone Number</div>
      <div class="field-value">${esc(data.phoneNumber) || '—'}</div>
    </div>
    <div class="field field-full">
      <div class="field-label">Address</div>
      <div class="field-value">${esc(data.address) || '—'}</div>
    </div>
    <div class="field">
      <div class="field-label">Emergency Contact Name</div>
      <div class="field-value">${esc(data.emergencyContactName) || '—'}</div>
    </div>
    <div class="field">
      <div class="field-label">Emergency Contact Phone</div>
      <div class="field-value">${esc(data.emergencyContactPhone) || '—'}</div>
    </div>
    <div class="field">
      <div class="field-label">Designation</div>
      <div class="field-value">${esc(data.designation) || '—'}</div>
    </div>
    <div class="field">
      <div class="field-label">Date of Joining</div>
      <div class="field-value">${esc(data.dateOfJoining) || '—'}</div>
    </div>
    <div class="field field-full">
      <div class="field-label">Previous Experience</div>
      <div class="field-value" style="white-space:pre-wrap">${esc(data.previousExperience) || '—'}</div>
    </div>
    <div class="field">
      <div class="field-label">Processed by (Supervisor)</div>
      <div class="field-value">${esc(data.supervisorName) || '—'}</div>
    </div>
    <div class="field">
      <div class="field-label">Date</div>
      <div class="field-value">${new Date().toLocaleDateString('en-IN', { day:'2-digit', month:'long', year:'numeric' })}</div>
    </div>
  </div>

  <div class="sig-row">
    <div class="sig-box">
      <div class="line"></div>
      <div class="label">Worker Signature</div>
    </div>
    <div class="sig-box">
      <div class="line"></div>
      <div class="label">Supervisor Signature &amp; Stamp</div>
    </div>
  </div>

  <div class="footer">
    Generated by SASEC Engineering Internal Portal &mdash; ${new Date().toLocaleString('en-IN')}
  </div>

  <script>
    window.addEventListener('load', function() {
      window.print();
      window.addEventListener('afterprint', function() { window.close(); });
    });
  </script>
</body></html>`)
  win.document.close()
}

// ── Escape HTML for safe injection into print window ─────────
function esc(s) {
  return String(s ?? '')
    .replace(/&/g, '&amp;')
    .replace(/</g, '&lt;')
    .replace(/>/g, '&gt;')
    .replace(/"/g, '&quot;')
}

// ── Supabase helpers ──────────────────────────────────────────

export function insertLeaveDisclaimer(row) {
  return supabase
    .from('leave_disclaimers')
    .insert(row)
    .select()
    .single()
}

export function updateLeaveDisclaimerScan(id, scanPath) {
  return supabase
    .from('leave_disclaimers')
    .update({ scan_path: scanPath })
    .eq('id', id)
}

export function fetchMyLeaveDisclaimers(supervisorId) {
  return supabase
    .from('leave_disclaimers')
    .select('id, worker_name, worker_phone, leave_start, leave_end, supervisor_name, scan_path, created_at')
    .eq('supervisor_id', supervisorId)
    .order('created_at', { ascending: false })
}

export async function fetchAllLeaveDisclaimers() {
  const { data, error } = await supabase
    .from('leave_disclaimers')
    .select('id, supervisor_id, worker_name, worker_phone, leave_start, leave_end, supervisor_name, scan_path, created_at')
    .order('created_at', { ascending: false })
  if (error) return { data: null, error }
  return enrichWithSupervisorNames(data)
}

export function insertOnboardingForm(row) {
  return supabase
    .from('onboarding_forms')
    .insert(row)
    .select()
    .single()
}

export function updateOnboardingScan(id, scanPath) {
  return supabase
    .from('onboarding_forms')
    .update({ scan_path: scanPath })
    .eq('id', id)
}

export function fetchMyOnboardingForms(supervisorId) {
  return supabase
    .from('onboarding_forms')
    .select('id, full_name, phone_number, designation, date_of_joining, supervisor_name, scan_path, created_at')
    .eq('supervisor_id', supervisorId)
    .order('created_at', { ascending: false })
}

export async function fetchAllOnboardingForms() {
  const { data, error } = await supabase
    .from('onboarding_forms')
    .select('id, supervisor_id, full_name, phone_number, designation, date_of_joining, supervisor_name, scan_path, created_at')
    .order('created_at', { ascending: false })
  if (error) return { data: null, error }
  return enrichWithSupervisorNames(data)
}

// Shared: batch-fetch supervisor names and attach
async function enrichWithSupervisorNames(data) {
  const ids = [...new Set((data || []).map((r) => r.supervisor_id))]
  let nameById = {}
  if (ids.length > 0) {
    const { data: profs } = await supabase
      .from('profiles')
      .select('id, full_name')
      .in('id', ids)
    for (const p of profs || []) nameById[p.id] = p.full_name
  }
  return {
    error: null,
    data: (data || []).map((r) => ({
      ...r,
      supervisor_account_name: nameById[r.supervisor_id] || r.supervisor_name || 'Supervisor',
    })),
  }
}

// ── Scan upload ───────────────────────────────────────────────

export async function uploadScan(supervisorId, formType, formId, file) {
  const ext  = file.name.split('.').pop().toLowerCase() || 'jpg'
  const path = `${supervisorId}/${formType}/${formId}.${ext}`
  const { error } = await supabase.storage
    .from(SCAN_BUCKET)
    .upload(path, file, { contentType: file.type, upsert: true })
  if (error) return { error, path: null }
  return { error: null, path }
}

export async function getScanUrl(path) {
  if (!path) return null
  const { data } = await supabase.storage
    .from(SCAN_BUCKET)
    .createSignedUrl(path, 60 * 60)
  return data?.signedUrl ?? null
}
